export type CuratedName = {
  name: string;
};

const LEADING_ARTICLE = /^(a|an|the)\s+/i;

export function toSortKey(name: string) {
  return name
    .normalize("NFKD")
    .replace(LEADING_ARTICLE, "")
    .replace(/\s+/g, " ")
    .trim();
}

const CURATED_NAMES_RAW: CuratedName[] = [
  { name: "Aaron Douglas" },
  { name: "A$AP Rocky" },
  { name: "Abbey Lincoln" },
  { name: "Abdias do Nascimento" },
  { name: "Aimé Césaire" },
  { name: "Alain LeRoy Locke" },
  { name: "Alberta Hunter" },
  { name: "Alexander Crummell" },
  { name: "Alton Mason" },
  { name: "André 3000" },
  { name: "André Leon Talley" },
  { name: "Archibald Motley" },
  { name: "Arthur Ashe" },
  { name: "Baloji" },
  { name: "Bayard Rustin" },
  { name: "Bessie Smith" },
  { name: "Bill Bojangles Robinson" },
  { name: "Billie Holiday" },
  { name: "Billy Eckstine" },
  { name: "Black Herman" },
  { name: "Cab Calloway" },
  { name: "Cam Newton" },
  { name: "Celia Cruz" },
  { name: "Charles White" },
  { name: "Claude McKay" },
  { name: "Coleman Hawkins" },
  { name: "Colman Domingo" },
  { name: "Countee Cullen" },
  { name: "Dapper Dan" },
  { name: "David Adjaye" },
  { name: "Diana Ross" },
  { name: "Dizzy Gillespie" },
  { name: "Don Cornelius" },
  { name: "Donald Byrd" },
  { name: "Duke Ellington" },
  { name: "Edward Enninful" },
  { name: "Elizabeth Keckley" },
  { name: "Essex Hemphill" },
  { name: "Ethel Waters" },
  { name: "Fela Kuti" },
  { name: "Floyd Patterson" },
  { name: "Frederick Douglass" },
  { name: "George Bridgetower" },
  { name: "Grace Jones" },
  { name: "Gregory Hines" },
  { name: "Harold Jackman" },
  { name: "Harry Belafonte" },
  { name: "Hazel Scott" },
  { name: "Iman" },
  { name: "Ira Aldridge" },
  { name: "Isaac Hayes" },
  { name: "James Baldwin" },
  { name: "James Brown" },
  { name: "James Van Der Zee" },
  { name: "Janelle Monáe" },
  { name: "Jay-Z" },
  { name: "Jean-Michel Basquiat" },
  { name: "Jidenna" },
  { name: "Josephine Baker" },
  { name: "Julius Soubise" },
  { name: "Kelela" },
  { name: "Kofi Siriboe" },
  { name: "Kwame Brathwaite" },
  { name: "Langston Hughes" },
  { name: "Lena Horne" },
  { name: "Lewis Hamilton" },
  { name: "Little Richard" },
  { name: "Lloyd Richards" },
  { name: "Louis Armstrong" },
  { name: "Madam C. J. Walker" },
  { name: "Malcolm X" },
  { name: "Marian Anderson" },
  { name: "Marsha P. Johnson" },
  { name: "Marvin Gaye" },
  { name: "Mary Church Terrell" },
  { name: "Miles Davis" },
  { name: "Moses Sumney" },
  { name: "Muhammad Ali" },
  { name: "Nina Mae McKinney" },
  { name: "Nina Simone" },
  { name: "Noble Sissle" },
  { name: "Olaudah Equiano" },
  { name: "Oscar Micheaux" },
  { name: "Ozwald Boateng" },
  { name: "Paul Robeson" },
  { name: "Pharrell Williams" },
  { name: "Prince" },
  { name: "Questlove" },
  { name: "Quincy Jones" },
  { name: "Richard Bruce Nugent" },
  { name: "Richard Roundtree" },
  { name: "Romare Bearden" },
  { name: "RuPaul" },
  { name: "Sammy Davis Jr." },
  { name: "Sidney Poitier" },
  { name: "Solange Knowles" },
  { name: "Stokely Carmichael" },
  { name: "Sun Ra" },
  { name: "Teddy Pendergrass" },
  { name: "The Nicholas Brothers" },
  { name: "Theaster Gates" },
  { name: "Thelonious Monk" },
  { name: "Tommie Smith" },
  { name: "Toussaint Louverture" },
  { name: "Tyler, the Creator" },
  { name: "Usher" },
  { name: "Virgil Abloh" },
  { name: "W. E. B. Du Bois" },
  { name: "Wynton Marsalis" },
  { name: "Yasiin Bey" },
  { name: "Yinka Shonibare" },
  { name: "Zora Neale Hurston" },
  { name: "Amiri Baraka" },
  { name: "Bobby Short" },
  { name: "Charles Mingus" },
  { name: "Cornel West" },
  { name: "Donny Hathaway" },
  { name: "Dorothy Dandridge" },
  { name: "Earl Grant" },
  { name: "Eartha Kitt" },
  { name: "Eddie Kendricks" },
  { name: "Ernie Barnes" },
  { name: "Eugene Bullard" },
  { name: "Gil Scott-Heron" },
  { name: "Gordon Parks" },
  { name: "Herbie Hancock" },
  { name: "Huey P. Newton" },
  { name: "Jack Johnson" },
  { name: "Jackie Wilson" },
  { name: "John Coltrane" },
  { name: "Johnny Hartman" },
  { name: "Jules Lion" },
  { name: "Leontyne Price" },
  { name: "Lorraine Hansberry" },
  { name: "Mahershala Ali" },
  { name: "Masego" },
  { name: "Maxwell" },
  { name: "Nat King Cole" },
  { name: "Nicholas Daley" },
  { name: "Nipsey Hussle" },
  { name: "Otis Redding" },
  { name: "Patrick Kelly" },
  { name: "Ralph Ellison" },
  { name: "Ray Charles" },
  { name: "Sam Cooke" },
  { name: "Sly Stone" },
  { name: "Smokey Robinson" },
  { name: "Stevie Wonder" },
  { name: "Telfar Clemens" },
  { name: "Willi Smith" }
];

export const CURATED_NAMES = [...CURATED_NAMES_RAW].sort((left, right) =>
  toSortKey(left.name).localeCompare(toSortKey(right.name), "en", {
    sensitivity: "base"
  })
);
